### ISSUE TITLE
Fix Responsiveness Issues Across Multiple Screen Sizes

### ISSUE THREAD

**Issue by VanshChitransh** [NK-Works/Kalp-Vote#1]
### Description
There are elements on the page that are not responsive across different screen sizes. This issue causes the layout to break or content to overflow on smaller screens like mobile devices.

### Expected Behavior
- The layout should be adaptive and responsive across various screen sizes (mobile, tablet, desktop).
- Content should be legible, and no elements should overlap or overflow.

### Current Behavior
- Describe the specific elements or sections that are not responsive.
- Mention if there are any elements overlapping, cutting off, or breaking on small screens.

### Screenshots
Please attach screenshots that show the responsiveness issues on different devices/screens.

#### Example:
| Desktop | Mobile |
| ------- | ------ |
![Screenshot from 2024-10-11 03-48-56](https://github.com/user-attachments/assets/4af9c454-cb6f-4afa-b14b-7b7515544314)

![Screenshot from 2024-10-11 03-49-17](https://github.com/user-attachments/assets/6afba011-9f97-4201-8196-c18dbff560d6)

### Steps to Reproduce
1. Open the website/page on a mobile or tablet device.
2. Identify elements that are not adapting to the screen size (e.g., buttons, images, div containers).
3. Verify if any content overflows or overlaps on smaller screens.

### Possible Solutions
- Suggest any potential fixes, like using media queries (`@media`) for CSS or refactoring flex/grid layout.
- Propose specific breakpoints for different screen sizes (e.g., 320px, 768px, 1024px).

### Device Information
Please provide the following information to help debug the issue:
- **Device:** [e.g., iPhone 12, Samsung Galaxy S21, iPad]
- **Browser:** [e.g., Chrome, Firefox, Safari]
- **Operating System:** [e.g., Android, iOS, Windows]

### Additional Context
- Any additional information that might help in fixing the issue, such as related pull requests or previous discussions.

---

### Priority
- [ ] High

### Labels
- `bug`
- `UI/UX`
- `responsiveness`

---

### Assignees
- Add team members who will address this issue.

**Comment by VanshChitransh** [comment]
@omsenpaiii I would love to work on this issue.

**Comment by NK-Works** [comment]
@VanshChitransh go ahead. I am looking forward to your work :)
