### ISSUE TITLE
Website Unresponsiveness

### ISSUE THREAD

**Issue by mayank-0789** [NK-Works/Kalp-Vote#2]
# Issue: Website Unresponsiveness

## Description
The website becomes unresponsive under certain conditions, causing delays in user interactions and slow page load times. This issue affects user experience and could lead to loss of traffic or conversions.
Not properly working across different devices

### Expected Behavior:
The website should respond promptly to user inputs and load pages within an acceptable timeframe (e.g., under 2 seconds for standard content).

### Actual Behavior:
- The page freezes for up to **10 seconds** or more before responding.
- In some cases, the browser displays a "Page Unresponsive" message.
- Scrolling and clicking elements (e.g., buttons, links) have a delayed response.

## Screenshots/Logs:
<img width="543" alt="Screenshot 2024-10-11 at 3 51 46 AM" src="https://github.com/user-attachments/assets/46f7ab08-b812-473d-9711-d1c6cd656bc9">

**Comment by mayank-0789** [comment]
Hey @NK-Works please assign this issue to me

**Comment by NK-Works** [comment]
@mayank-0789 already assigned the issue as someone asked earlier...
Work on something else...
Looking forward to it :)
