### ISSUE TITLE
Fix Non-Functional Buttons and Implement Temporary 404 Page

### ISSUE THREAD

**Issue by VanshChitransh** [NK-Works/Kalp-Vote#3]
### Description
Several buttons on the website, such as **Explore** and **Get in Touch**, are currently non-functional. Clicking them does not lead to any action or page. We need to address this by either linking them to the proper destination or adding a temporary **404 page** until the actual content is added.

### Expected Behavior
- When a user clicks on buttons like **Explore**, **Get in Touch**, etc., they should either be redirected to the appropriate page or see a placeholder 404 page.
- The 404 page should clearly inform users that the content is not yet available and provide navigation options back to the homepage.

### Current Behavior
- Buttons do not trigger any navigation or action, making them non-functional.

### Steps to Reproduce
1. Visit the website.
2. Click on buttons such as **Explore** or **Get in Touch**.
3. Notice that no page loads or action occurs.

### Suggested Fixes
- Implement a **404 page** as a temporary solution for the buttons that are non-functional until their respective content is available.
- Ensure the 404 page has:
  - A user-friendly message explaining that the page/content is under construction.
  - A **Back to Home** or **Go Back** button to return users to the main page.

### Device Information
- **Device:** [e.g., MacBook, iPhone X]
- **Browser:** [e.g., Chrome, Firefox]
- **Operating System:** [e.g., macOS, iOS]

---

### Priority
- [ ] High

### Labels
- `bug`
- `UI/UX`
- `navigation`

---

### Assignees
- Add team members responsible for fixing this issue.

**Comment by VanshChitransh** [comment]
@omsenpaiii Can you please assign this issue to me?

**Comment by arun0452** [comment]
Could you Please assign this issue to me?.
 I have wide range of experience in React and Next JS

**Comment by NK-Works** [comment]
@arun0452 @VanshChitransh asked first so I will assign...
If he doesn't solve it within 3 days then I will also assign you as well.
@VanshChitransh I am looking forward to your work :)
@arun0452 in the mean time wok on something else :)
